/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crunion;

import java.io.*;

/**
 *
 * @author joses
 */
public class CRUnion extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CRUnion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainTabbedPanel = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        textFieldNombreClienteRegistrar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonRegistrarCliente = new javax.swing.JButton();
        textFieldClienteRegistrar = new javax.swing.JTextField();
        textFieldIdClienteRegistrar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textFieldApellidosClienteRegistrar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textFieldNacionalidadClienteRegistrar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textFieldEdadClienteRegistrar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        comboBoxClienteEliminar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        buttonEliminarCliente = new javax.swing.JButton();
        textFieldClienteActualizar = new javax.swing.JTextField();
        buttonRegistrarClienteActualizar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        textFieldEdadClienteActualizar = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        textFieldNacionalidadClienteActualizar = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        textFieldApellidosClienteActualizar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textFieldNombreClienteActualizar = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        comboBoxClienteActualizar = new javax.swing.JComboBox<>();
        panelConversiones = new javax.swing.JPanel();
        textFieldCantidadMoneda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboBoxMonedaOrigen = new javax.swing.JComboBox<>();
        comboBoxMonedaDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonCovertir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxCliente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textFieldTransaccionReciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaHistorialTransacciones = new javax.swing.JTextArea();
        panelConfiguracion = new javax.swing.JPanel();
        textFieldNombreMonedaAgregar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buttonMonedaAgregar = new javax.swing.JButton();
        comboBoxMonedaActualizar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        textFieldNotificacionMonedaActualizar = new javax.swing.JTextField();
        textFieldCompraMonedaAgregar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textFieldVentaMonedaAgregar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textFieldCompraMonedaActualizar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textFieldVentaMonedaActualizar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        buttonMonedaActualizar = new javax.swing.JButton();
        textFieldNotificacionMonedaAgregar = new javax.swing.JTextField();
        panelConsultaConversionesCliente = new javax.swing.JPanel();
        buttonConsultarConversionCliente = new javax.swing.JButton();
        comboBoxConsultarConversionCliente = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableConversionesCliente = new javax.swing.JTable();
        panelConsultaConversiones = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ConsultaConversiones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textFieldNombreClienteRegistrar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel7.setText("Nombre del Cliente a Registrar");

        buttonRegistrarCliente.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        buttonRegistrarCliente.setText("REGISTRAR");
        buttonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarClienteActionPerformed(evt);
            }
        });

        textFieldClienteRegistrar.setEditable(false);
        textFieldClienteRegistrar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N

        textFieldIdClienteRegistrar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel19.setText("ID del Cliente a Registrar");

        textFieldApellidosClienteRegistrar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel20.setText("Apellidos del Cliente a Registrar");

        textFieldNacionalidadClienteRegistrar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel21.setText("Nacionalidad del Cliente a Registrar");

        textFieldEdadClienteRegistrar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel22.setText("Edad del Cliente a Registrar");

        comboBoxClienteEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel9.setText("Cliente");

        buttonEliminarCliente.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        buttonEliminarCliente.setText("ELIMINAR CLIENTE");
        buttonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarClienteActionPerformed(evt);
            }
        });

        textFieldClienteActualizar.setEditable(false);
        textFieldClienteActualizar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N

        buttonRegistrarClienteActualizar.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        buttonRegistrarClienteActualizar.setText("ACTUALIZAR");
        buttonRegistrarClienteActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarClienteActualizarActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel24.setText("Edad del Cliente a Actualizar");

        textFieldEdadClienteActualizar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel25.setText("Nacionalidad del Cliente a Actualizar");

        textFieldNacionalidadClienteActualizar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel26.setText("Apellidos del Cliente a Actualizar");

        textFieldApellidosClienteActualizar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel10.setText("Nombre del Cliente a Actualizar");

        textFieldNombreClienteActualizar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel27.setText("ID del Cliente a Actualizar");

        comboBoxClienteActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(textFieldApellidosClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldIdClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombreClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(474, 474, 474))
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEliminarCliente)
                    .addComponent(textFieldEdadClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNacionalidadClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRegistrarCliente)
                    .addComponent(comboBoxClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(355, 355, 355)
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNombreClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldApellidosClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldEdadClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNacionalidadClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonRegistrarClienteActualizar)
                                    .addGroup(panelClientesLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel24)))
                                    .addComponent(comboBoxClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addComponent(comboBoxClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNombreClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldApellidosClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNacionalidadClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldEdadClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonRegistrarClienteActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addComponent(textFieldIdClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNombreClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldApellidosClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNacionalidadClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldEdadClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonRegistrarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldClienteRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(comboBoxClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(buttonEliminarCliente)
                .addGap(46, 46, 46))
        );

        mainTabbedPanel.addTab("Clientes", panelClientes);

        textFieldCantidadMoneda.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad a convertir");

        comboBoxMonedaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxMonedaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("Moneda Destino");

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setText("Moneda Origen");

        buttonCovertir.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        buttonCovertir.setText("CONVERTIR");
        buttonCovertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCovertirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Corbel", 2, 14)); // NOI18N
        jLabel4.setText("<html>Compras entre 3000 y 6000:<br>&nbsp;&nbsp;&nbsp;&nbsp;precioCompra = precioCompra + 0.15*diferenciaVentaCompra<br>Compras entre 6000 y 9000:<br>&nbsp;&nbsp;&nbsp;&nbsp;precioCompra = precioCompra + 0.25*diferenciaVentaCompra<br>Compras mayores a 9000<br>&nbsp;&nbsp;&nbsp;&nbsp;precioCompra = precioCompra + 0.35*diferenciaVentaCompra</html>");

        jLabel5.setFont(new java.awt.Font("Corbel", 2, 14)); // NOI18N
        jLabel5.setText("<html>Ventas entre 3000 y 6000 impuesto de 1%<br>Ventas entre 6000 y 9000 impuesto de 2%<br>Ventas mayores a 9000 impuesto de 3%<br></html>");

        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel6.setText("Cliente");

        textFieldTransaccionReciente.setEditable(false);
        textFieldTransaccionReciente.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N

        textAreaHistorialTransacciones.setEditable(false);
        textAreaHistorialTransacciones.setColumns(20);
        textAreaHistorialTransacciones.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        textAreaHistorialTransacciones.setRows(5);
        jScrollPane1.setViewportView(textAreaHistorialTransacciones);

        javax.swing.GroupLayout panelConversionesLayout = new javax.swing.GroupLayout(panelConversiones);
        panelConversiones.setLayout(panelConversionesLayout);
        panelConversionesLayout.setHorizontalGroup(
            panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConversionesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldTransaccionReciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(panelConversionesLayout.createSequentialGroup()
                        .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldCantidadMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCovertir)
                            .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelConversionesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)))
                            .addGroup(panelConversionesLayout.createSequentialGroup()
                                .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxMonedaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelConversionesLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelConversionesLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2))
                                    .addComponent(comboBoxMonedaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelConversionesLayout.setVerticalGroup(
            panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConversionesLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelConversionesLayout.createSequentialGroup()
                        .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldCantidadMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxMonedaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMonedaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCovertir)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldTransaccionReciente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        mainTabbedPanel.addTab("Conversiones", panelConversiones);

        textFieldNombreMonedaAgregar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setText("Nombre de la moneda a agregar");

        buttonMonedaAgregar.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        buttonMonedaAgregar.setText("AGREGAR");
        buttonMonedaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMonedaAgregarActionPerformed(evt);
            }
        });

        comboBoxMonedaActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel13.setText("Moneda a actualizar");

        textFieldNotificacionMonedaActualizar.setEditable(false);
        textFieldNotificacionMonedaActualizar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N

        textFieldCompraMonedaAgregar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel14.setText("Precio de Compra");

        textFieldVentaMonedaAgregar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel15.setText("Precio de Venta");

        textFieldCompraMonedaActualizar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel16.setText("Nuevo precio de Compra");

        textFieldVentaMonedaActualizar.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel17.setText("Nuevo precio de Venta");

        buttonMonedaActualizar.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        buttonMonedaActualizar.setText("ACTUALIZAR");
        buttonMonedaActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMonedaActualizarActionPerformed(evt);
            }
        });

        textFieldNotificacionMonedaAgregar.setEditable(false);
        textFieldNotificacionMonedaAgregar.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N

        javax.swing.GroupLayout panelConfiguracionLayout = new javax.swing.GroupLayout(panelConfiguracion);
        panelConfiguracion.setLayout(panelConfiguracionLayout);
        panelConfiguracionLayout.setHorizontalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldNombreMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCompraMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldVentaMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))
                    .addComponent(buttonMonedaAgregar)
                    .addComponent(textFieldNotificacionMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldNotificacionMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCompraMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldVentaMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)))
                    .addComponent(buttonMonedaActualizar))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        panelConfiguracionLayout.setVerticalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(comboBoxMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(textFieldNombreMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(21, 21, 21)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(textFieldCompraMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(textFieldCompraMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(textFieldVentaMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(textFieldVentaMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMonedaAgregar)
                    .addComponent(buttonMonedaActualizar))
                .addGap(29, 29, 29)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNotificacionMonedaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNotificacionMonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        mainTabbedPanel.addTab("Configuracion de Conversion y Monedas", panelConfiguracion);

        buttonConsultarConversionCliente.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        buttonConsultarConversionCliente.setText("CONSULTAR");
        buttonConsultarConversionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultarConversionClienteActionPerformed(evt);
            }
        });

        comboBoxConsultarConversionCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel23.setText("Cliente");

        tableConversionesCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID  Transaccion", "Moneda Origen", "Moneda Destino", "Monto Origen", "Monto Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableConversionesCliente);

        javax.swing.GroupLayout panelConsultaConversionesClienteLayout = new javax.swing.GroupLayout(panelConsultaConversionesCliente);
        panelConsultaConversionesCliente.setLayout(panelConsultaConversionesClienteLayout);
        panelConsultaConversionesClienteLayout.setHorizontalGroup(
            panelConsultaConversionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaConversionesClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelConsultaConversionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxConsultarConversionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConsultaConversionesClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelConsultaConversionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonConsultarConversionCliente)
                            .addComponent(jLabel23))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultaConversionesClienteLayout.setVerticalGroup(
            panelConsultaConversionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaConversionesClienteLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelConsultaConversionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConsultaConversionesClienteLayout.createSequentialGroup()
                        .addComponent(comboBoxConsultarConversionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(buttonConsultarConversionCliente)))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        mainTabbedPanel.addTab("Consultar Conversiones por Cliente", panelConsultaConversionesCliente);

        ConsultaConversiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID de transaccion", "ID de cliente", "Moneda Origen", "Moneda Destino", "Monto Origen", "Monto Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(ConsultaConversiones);

        javax.swing.GroupLayout panelConsultaConversionesLayout = new javax.swing.GroupLayout(panelConsultaConversiones);
        panelConsultaConversiones.setLayout(panelConsultaConversionesLayout);
        panelConsultaConversionesLayout.setHorizontalGroup(
            panelConsultaConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaConversionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultaConversionesLayout.setVerticalGroup(
            panelConsultaConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaConversionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addGap(112, 112, 112))
        );

        mainTabbedPanel.addTab("Consultar Conversiones por Moneda", panelConsultaConversiones);

        getContentPane().add(mainTabbedPanel, java.awt.BorderLayout.PAGE_START);
        actualizarComboBoxes();

        pack();
    }// </editor-fold>                        

    private void buttonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void buttonRegistrarClienteActualizarActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        // TODO add your handling code here:
    }                                                                

    private void buttonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void buttonCovertirActionPerformed(java.awt.event.ActionEvent evt) {                                               
        monedaOrigen = comboBoxMonedaOrigen.getSelectedItem().toString().toLowerCase();
        monedaDestino = comboBoxMonedaDestino.getSelectedItem().toString().toLowerCase();

        //Variable usada para guardar temporalmente el string procesado
        transaccionStringTmp = "";

        /**
         Este Try statement maneja la logica principal de GUI  y a su vez realiza el checkeo de la cantidad introducida
         Maneja las excepciones dependiendo de si la cantidad es un float, si es negativa o en el caso de ser 0 no realiza ningun calculo adicional y solo imprime 0 = 0
         */
        try {
            cantidadMonedaInicial = Float.parseFloat(textFieldCantidadMoneda.getText());

            if (cantidadMonedaInicial == 0) {
                // Escenario cuando cantidadMonedaIncial = 0
                transaccionStringTmp = String.format("%.2f %s equivalen a 0.00 %s", cantidadMonedaInicial, monedaOrigen, monedaDestino);
                textFieldTransaccionReciente.setText(transaccionStringTmp);
                textAreaHistorialTransacciones.append(transaccionStringTmp + NEWLINE);

            } else if (cantidadMonedaInicial < 0) {
                // Escenario cuando cantidad de moneda incial es negativa
                textFieldTransaccionReciente.setText(String.format("%.2f es una cantidad ilegal (no se admiten numeros negativos)", cantidadMonedaInicial));

            } else {
                /**
                 Escenario cuando la cantidad es valida y diferente de 0.
                 Imprime el calculo en la pantalla de la transaccion actual y tambien imprime la transaccion al historial de transaciones para visibilidad
                 */
                cantidadMonedaFinal = ConversionesNuevas.ConversionMonedas(cantidadMonedaInicial, monedaOrigen, monedaDestino);
                transaccionStringTmp = String.format("%.2f %s equivalen a %.2f %s", cantidadMonedaInicial, monedaOrigen, cantidadMonedaFinal, monedaDestino);
                textFieldTransaccionReciente.setText(transaccionStringTmp);
                textAreaHistorialTransacciones.append(transaccionStringTmp + NEWLINE);
                Helpers.agregarConversionToJson(CONVERSIONFILEPATH, monedaOrigen, monedaDestino, cantidadMonedaInicial, cantidadMonedaFinal);

            }
        } catch (java.lang.NumberFormatException ex) {
            /**
             Atrapa la excepcion en casos donde cantidadMonedaInicial no puede ser parseado como un float
             Imprime la excepcion a la consola usando el logger y tambien muestra un mensaje al usuario
             */
            textFieldTransaccionReciente.setText(String.format("\"%s\" es una cantidad ilegal", textFieldCantidadMoneda.getText()));
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.WARNING, null, ex);

        }
        // Reinicia el cuadro de texto de input
        textFieldCantidadMoneda.setText("");
    }                                              

    private void buttonMonedaAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        nuevaMoneda = textFieldNombreMonedaAgregar.getText();

        try {
            nuevaMonedaCompra = Float.parseFloat(textFieldCompraMonedaAgregar.getText());
            nuevaMonedaVenta = Float.parseFloat(textFieldVentaMonedaAgregar.getText());

            if (nuevaMonedaCompra > 0 && nuevaMonedaVenta > 0) {
                if (EquivalenciasNuevas.agregarNuevaMoneda(nuevaMoneda, nuevaMonedaVenta, nuevaMonedaCompra)) {
                    textFieldNotificacionMonedaAgregar.setText(String.format("Moneda \"%s\" agredada Compra: %.2f | Venta: %.2f ", nuevaMoneda, nuevaMonedaCompra, nuevaMonedaVenta));
                    actualizarComboBoxes();
                }
            } else {
                textFieldNotificacionMonedaAgregar.setText(String.format("Ni el precio de venta o el de compra pueden ser iguales o menores a cero"));
            }

        } catch (java.lang.NumberFormatException ex) {
            textFieldNotificacionMonedaAgregar.setText(String.format("Alguno de los valores es una cantidad ilegal (deben ser numeros). Compra:\"%s\" Venta:\"%s\"", textFieldCompraMonedaAgregar.getText(), textFieldVentaMonedaAgregar.getText()));
        } 
        textFieldCompraMonedaAgregar.setText("");
        textFieldVentaMonedaAgregar.setText("");
        textFieldNombreMonedaAgregar.setText(""); 
    }                                                   

    private void buttonMonedaActualizarActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        String nombreMoneda = comboBoxMonedaActualizar.getSelectedItem().toString().toLowerCase();
        try {
            monedaActualizarCompra = Float.parseFloat(textFieldCompraMonedaActualizar.getText());
            monedaActualizarVenta = Float.parseFloat(textFieldVentaMonedaActualizar.getText());

            if (monedaActualizarCompra > 0 && monedaActualizarVenta > 0) {
                if (EquivalenciasNuevas.actualizarEquivalencia(nombreMoneda, monedaActualizarVenta, monedaActualizarCompra)) {
                    textFieldNotificacionMonedaActualizar.setText(String.format("Nuevos valores de moneda \"%s\". Compra: %.2f | Venta: %.2f ", nombreMoneda, monedaActualizarCompra, monedaActualizarVenta));
                } else {
                    textFieldNotificacionMonedaActualizar.setText(String.format("La moneda con el nombre \"%s\" no existe", nombreMoneda));    
                }
            } else
            {
                textFieldNotificacionMonedaActualizar.setText(String.format("Ni el precio de venta o el de compra pueden ser iguales o menores a cero"));
            }

        } catch (java.lang.NumberFormatException ex) {
            textFieldNotificacionMonedaActualizar.setText(String.format("Alguno de los valores es una cantidad ilegal (deben ser numeros). Compra:\"%s\" Venta:\"%s\"", textFieldCompraMonedaActualizar.getText(), textFieldVentaMonedaActualizar.getText()));
        }

        textFieldCompraMonedaActualizar.setText("");
        textFieldVentaMonedaActualizar.setText("");
    }                                                      

    private void buttonConsultarConversionClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        // TODO add your handling code here:
    }                                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        File directory = new File("./");
        System.out.println(directory.getAbsolutePath());
        Equivalencias.getInstance(25);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUnion().setVisible(true);
            }
        });
    }

    private void actualizarComboBoxes () {
        
        comboBoxMonedaOrigen.setModel(new javax.swing.DefaultComboBoxModel(Equivalencias.getInstance().getDescripcionesMonedasValidas()));
        comboBoxMonedaDestino.setModel(new javax.swing.DefaultComboBoxModel(Equivalencias.getInstance().getDescripcionesMonedasValidas()));
        comboBoxMonedaActualizar.setModel(new javax.swing.DefaultComboBoxModel(Equivalencias.getInstance().getDescripcionesMonedasValidas()));
 
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable ConsultaConversiones;
    private javax.swing.JButton buttonConsultarConversionCliente;
    private javax.swing.JButton buttonCovertir;
    private javax.swing.JButton buttonEliminarCliente;
    private javax.swing.JButton buttonMonedaActualizar;
    private javax.swing.JButton buttonMonedaAgregar;
    private javax.swing.JButton buttonRegistrarCliente;
    private javax.swing.JButton buttonRegistrarClienteActualizar;
    private javax.swing.JComboBox<String> comboBoxCliente;
    private javax.swing.JComboBox<String> comboBoxClienteActualizar;
    private javax.swing.JComboBox<String> comboBoxClienteEliminar;
    private javax.swing.JComboBox<String> comboBoxConsultarConversionCliente;
    private javax.swing.JComboBox<String> comboBoxMonedaActualizar;
    private javax.swing.JComboBox<String> comboBoxMonedaDestino;
    private javax.swing.JComboBox<String> comboBoxMonedaOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane mainTabbedPanel;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelConsultaConversiones;
    private javax.swing.JPanel panelConsultaConversionesCliente;
    private javax.swing.JPanel panelConversiones;
    private javax.swing.JTable tableConversionesCliente;
    private javax.swing.JTextArea textAreaHistorialTransacciones;
    private javax.swing.JTextField textFieldApellidosClienteActualizar;
    private javax.swing.JTextField textFieldApellidosClienteRegistrar;
    private javax.swing.JTextField textFieldCantidadMoneda;
    private javax.swing.JTextField textFieldClienteActualizar;
    private javax.swing.JTextField textFieldClienteRegistrar;
    private javax.swing.JTextField textFieldCompraMonedaActualizar;
    private javax.swing.JTextField textFieldCompraMonedaAgregar;
    private javax.swing.JTextField textFieldEdadClienteActualizar;
    private javax.swing.JTextField textFieldEdadClienteRegistrar;
    private javax.swing.JTextField textFieldIdClienteRegistrar;
    private javax.swing.JTextField textFieldNacionalidadClienteActualizar;
    private javax.swing.JTextField textFieldNacionalidadClienteRegistrar;
    private javax.swing.JTextField textFieldNombreClienteActualizar;
    private javax.swing.JTextField textFieldNombreClienteRegistrar;
    private javax.swing.JTextField textFieldNombreMonedaAgregar;
    private javax.swing.JTextField textFieldNotificacionMonedaActualizar;
    private javax.swing.JTextField textFieldNotificacionMonedaAgregar;
    private javax.swing.JTextField textFieldTransaccionReciente;
    private javax.swing.JTextField textFieldVentaMonedaActualizar;
    private javax.swing.JTextField textFieldVentaMonedaAgregar;
    private String transaccionStringTmp;
    private String monedaOrigen;
    private String monedaDestino;
    private String nuevaMoneda;
    private float nuevaMonedaCompra;
    private float nuevaMonedaVenta;
    private float monedaActualizarCompra;
    private float monedaActualizarVenta;
    private float cantidadMonedaFinal;
    private float cantidadMonedaInicial;
    private final static String NEWLINE = "\n";
    private final static String CONVERSIONFILEPATH = "./data/conversiones.json";
    // End of variables declaration                   
}
